# Generated by Django 3.2.6 on 2022-04-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220424_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.IntegerField(default=1, verbose_name='角色'),
        ),
    ]
