# Generated by Django 3.2.6 on 2022-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
