# Generated by Django 3.2.6 on 2022-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='邮箱验证码'),
        ),
    ]
