# Generated by Django 3.2.6 on 2022-04-26 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('pregnancies', models.IntegerField(blank=True, null=True, verbose_name='怀孕次数')),
                ('glucose', models.IntegerField(blank=True, null=True, verbose_name='葡萄糖')),
                ('blood_pressure', models.IntegerField(blank=True, null=True, verbose_name='血压')),
                ('skin_thickness', models.IntegerField(blank=True, null=True, verbose_name='皮肤厚度')),
                ('insulin', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='胰岛素')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='身体质量指数')),
                ('pedigree_function', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='遗传特性')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('outcome', models.IntegerField(blank=True, null=True, verbose_name='预测结果,0正常/1发病')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '糖尿病数据',
                'verbose_name_plural': '糖尿病数据',
                'db_table': 'diabetes',
            },
        ),
    ]
