# Generated by Django 3.2.6 on 2022-04-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='删除标记'),
        ),
    ]
