# Generated by Django 3.2.6 on 2022-06-13 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('resume_name', models.CharField(max_length=100, verbose_name='简历名称')),
                ('resume_detail', models.JSONField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='简历附件')),
                ('profile', models.ImageField(blank=True, max_length=200, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='照片')),
                ('resume_type', models.CharField(choices=[('social', '社招'), ('compass', '校招'), ('internship', '实习')], default='social', max_length=25)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '简历数据库',
                'verbose_name_plural': '简历数据库',
                'db_table': 'resume',
            },
        ),
    ]
